### ISSUE TITLE
Go binding installation error

### ISSUE THREAD

**Issue by iamalsaher** [knightsc/gapstone#2]
```
go get -u github.com/bnagy/gapstone

# github.com/bnagy/gapstone
/tmp/go-build004807394/b001/_x006.o: In function `_cgo_5d1ff8dacc63_Cfunc_cs_regs_access':
/tmp/go-build/cgo-gcc-prolog:234: undefined reference to `cs_regs_access'
collect2: error: ld returned 1 exit status

```

Any idea why this might be happening, I am running the latest capstone from [capstone master](https://github.com/aquynh/capstone) and used these commands to install

```
git clone https://github.com/aquynh/capstone.git
cd capstone
./make.sh default -j8
sudo ./make.sh install

```

**Comment by knightsc** [comment]
@iamalsaher It looks like you're using the old gapstone repo. You should be doing

`go get -u github.com/knightsc/gapstone`

Give that a try and let me know if it works.

**Comment by iamalsaher** [comment]
```go get -u github.com/knightsc/gapstone                 
# github.com/knightsc/gapstone
/tmp/go-build404890597/b001/_x006.o: In function `_cgo_3a2c9a4ced20_Cfunc_cs_regs_access':
/tmp/go-build/cgo-gcc-prolog:234: undefined reference to `cs_regs_access'
collect2: error: ld returned 1 exit status
```

Nope, gives the same issue

**Comment by knightsc** [comment]
`cs_regs_access` was added in Capstone 4. Is it possible there's some other version of Capstone installed and when you're building the Go bindings it's trying to link against some system version? Is this on Linux?

**Comment by iamalsaher** [comment]
Yes, I am on linux

**Comment by iamalsaher** [comment]
I am using the latest capstone from the first comment I mentioned

**Comment by knightsc** [comment]
`cs_regs_access` exists in the Capstone `master` branch. I would suggest searching your system to see if there are multiple versions of Capstone installed. I know on some Linux distros if you install capstone using the package manager you'll get version 3. Even if you download and compiled version 4 and installed if you have two versions installed it might be causing a conflict

**Comment by iamalsaher** [comment]
Can you tell me how to do that, I am googling literally that, cannot seem to find anything

**Comment by iamalsaher** [comment]
Okay it works now, I had a libcapstone-dev installed

**Comment by knightsc** [comment]
👍

**Comment by knightsc** [comment]
You might want to also make sure this is removed as well

sudo apt remove libcapstone3
