### ISSUE TITLE
Is it possible to update the next branch to be in sync with capstone's again?

### ISSUE THREAD

**Issue by blacktop** [knightsc/gapstone#3]
Was hoping to play with the new ARMv8.3 stuff?

**Comment by knightsc** [comment]
@blacktop Is there a new release of Capstone? or is the ARMv8.3 stuff just new in Capstone master?

**Comment by blacktop** [comment]
@aquynh hasn't cut a release version for 5.0 yet (I know he's been super busy with the new release of **qiling**), but the changes are in the `next` branch now.

**Comment by knightsc** [comment]
Ahh gotcha. I'll try to take a look over this coming week

**Comment by knightsc** [comment]
@blacktop I just updated the `next` branch. Give https://github.com/knightsc/gapstone/tree/next a spin and let me know if you hit any issues.
